[package]
name = "eon-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "_eon"
crate-type = ["cdylib"]
path = "src/eon/lib.rs"

[dependencies]
eon = "0.2.0"
pyo3 = { version = "0.22.0", features = ["extension-module", "abi3-py38", "serde"] }
vec1 = "1.12"
